# Book settings
title: プログラミング1
author: Naruaki TOMA
logo: './figs/prog1.pdf'
copyright: "2021"

#only_build_toc_files: true

repository:
    url: https://github.com/naltoma/python_intro2021
    branch: main

launch_buttons:
#    notebook_interface: "jupyterlab"
    notebook_interface: "classic"
    colab_url: "https://colab.research.google.com"
    binderhub_url: "https://mybinder.org"
    thebe: true

html:
    use_repository_button: true

sphinx:
    config:
        html_extra_path: ['assets']
